export const FILE_HEADER_ROWS = 2
export const FILE_TAIL_ROWS = 2
export const COMPANY_NAME_POSITION_START = 33
export const COMPANY_NAME_POSITION_END = 73
export const COMPANY_ADDRESS_POSITION_START = 73
export const COMPANY_ADDRESS_POSITION_END = 153
